### ISSUE TITLE
Add ability to exclude dependencies

### ISSUE THREAD

**Issue by zastrowm** [LarsSkovslund/NuGet.Package.Builder#10]
I have `JetBrains.Annotations` as a nuget/dll dependency, but for the nuget package.  It'd be nice if either that specific package was excluded, or there was a way to exclude dependencies

**Comment by LarsSkovslund** [comment]
You can exclude a package by setting ``developmentDependency="true"`` in the packages.config for the given dependency e.g. ``<package id="JetBrains.Annotations" version="1.0.0.0" targetFramework="net45" developmentDependency="true" />``.

Cheers
  Lars

**Comment by zastrowm** [comment]
Thanks, I wasn't aware of `developmentDependency` in packages.config.
