### ISSUE TITLE
Informal version in file name is broken

### ISSUE THREAD

**Issue by erdmenchen** [LarsSkovslund/NuGet.Package.Builder#11]
When updating from 1.08 to 1.09, nuget package files names include the file version instead of the informal version of the target assembly.

In 1.08 when configured, the informal version was used in the file name.
In 1.09 the file version is used in the file name, no matter what is configured.

**Comment by erdmenchen** [comment]
Sorry, issue found: When the informal version has a space character, then it reverts to the file version.

But spaces in the informal version are allowed in semantic versions see as described at http://semver.org.

**Comment by LarsSkovslund** [comment]
Thanks for sharing :-)

Cheers
  Lars
