### ISSUE TITLE
Version to Publish

### ISSUE THREAD

**Issue by martinlevington** [LarsSkovslund/NuGet.Package.Builder#12]
after upgrading to version 1.0.10 i am seeing a different behavior when building a project.

I have my projects set to publish on build.

In version 1.0.9 after a build the latest version would be uploaded.

i.e. project.1.0.44

with NuGet.Package.Builder.1.0.10  if the folder that contains the packed projects contains existing older versions. e.g.
project.1.0.40
project.1.0.41
project.1.0.42
project.1.0.43
project.1.0.44

the oldest file get published to the nuget server and not the newest built project. With the NuGet.Package.Builder.1.0.9 the newest file would be published.

**Comment by LarsSkovslund** [comment]
Hi Martin,

Can you please try ``1.0.11-pre01`` to verify that this fixes your issue?

Cheers
  Lars
