### ISSUE TITLE
Update version of nuget exe used

### ISSUE THREAD

**Issue by benardmens** [LarsSkovslund/NuGet.Package.Builder#17]
We have an issue with v 1.0.10 where we are targeting .Net 4.5.2 and are unable to pull down packages which have .NetStandard folders in them. 

For example adding Serilog version 2.4.0 and attempting a build will give "error : System.InvalidOperationException: 'Serilog' already has a dependency defined for 'Microsoft.CSharp' ".

This is resolved by updating the nuget version from 3.3.0.212 to 3.5.0 causes the build to succeed. Would it be possible to do this update?

**Comment by stefbast** [comment]
I've created a pull request for this cfr https://github.com/LarsSkovslund/NuGet.Package.Builder/pull/18

**Comment by LarsSkovslund** [comment]
Version 1.0.11-pre02 is now available on nuget.org.

Let me know if you find any issues,

Cheers
  Lars
