### ISSUE TITLE
Build error on empty description

### ISSUE THREAD

**Issue by habakuk007** [LarsSkovslund/NuGet.Package.Builder#2]
Hi,

another bug i found (that is easy to workaround).

If the assembly description is empty, like this:

     <Assembly: AssemblyDescription("")>

And I try to use it in the nuspec file like this:

        <description>$description$</description>

I get this error:

      1>C:\blabla\packages\NuGet.Package.Builder.1.0.7\build\NuGet.Package.Builder.targets(28,3): error : System.InvalidOperationException: The replacement token 'description' has no value.

But it is easy to fix. If I put something in the `AssemblyDescription` it works.

Best regards!
   Stefan

**Comment by LarsSkovslund** [comment]
Hi Stefan,

This is expected behavior as the library uses NuGet.exe underneath the covers that throws the exception.

NB: I'll close the issue as Wontfix as its outside the sphere if this package.

Cheers
  Lars
