### ISSUE TITLE
Nuget.Package.Builder seen as a dependency

### ISSUE THREAD

**Issue by nix63** [LarsSkovslund/NuGet.Package.Builder#4]
When I import in a new project a package created using Nuget.Package.Builder, NPB is added as a dependency of this package. 
How may I avoid this?

**Comment by LarsSkovslund** [comment]
Hi nix63,

NPB is added as a `developmentDependency` package to avoid you scenario.
You can see this in the packages.config file where an entry like this `<package id="NuGet.Package.Builder" version="1.0.9" targetFramework="net46" developmentDependency="true" />` should be present.

Make sure the `developmentDependency` is set to `true` and you should be good to go.

Cheers
  Lars

**Comment by nix63** [comment]
Thanks, this fix the problem. 
Is it possible to make it the default when adding Nuget.Packag.Builder to a project?

**Comment by LarsSkovslund** [comment]
It is the default :-), I know of a bug (now fixed) in nuget where the `developmentDependency`is not persisted correctly. If you are not running the lates NuGet Package Manager try updating it.

Cheers

**Comment by nix63** [comment]
I'm using Nuget 2.8.60723.765 in Visual studio 2013. I've added the package using the nuget package manager console command prompt. I've removed and reinstalled Nuget.Package.Manager from the command prompt and the developmentDependecy=true is not added, while if you use the Gui it is correctly added.

**Comment by LarsSkovslund** [comment]
Interesting observation, unfortunately I don't have VS2013 and using VS2015 with `Package Manager Console Host Version 3.2.0.10516` it works as expected. None the less this seems to be [a general tools issue with 2.8.x](http://stackoverflow.com/questions/31363274/nuget-developmentdependency-not-working-when-package-installed-from-gallery) and therefor utterly out of my control.

The only option I have here is to suggest the workaround of settings the `developmentDependency` to `true` manually when using `Package Manager Console Host` from VS2013 :-(

Cheers
  Lars

**Comment by LarsSkovslund** [comment]
I'll close this issue as it is related to a bug in NuGet Package Manager Console 2.8.x.
