### ISSUE TITLE
Assembly not found

### ISSUE THREAD

**Issue by habakuk007** [LarsSkovslund/NuGet.Package.Builder#5]
Hi,
i added a new c#-project to my solution which mainly contains from vb-projects (don't know whether this is relevant).

No I get this error message: `NuGet.CommandLineException: "C:\US\Documents\SourceCode\bb-lp\LP\bin\Release\Portable.L\Portable.L.dll" was not found.` 

The error message tells the truth, as all assemblies are located in the output directory `C:\US\Documents\SourceCode\bb-lp\LP\bin\Release\` (including Portable.L.dll).

Any idea how I can fix the path? 

Best regards!
   Stefan

**Comment by LarsSkovslund** [comment]
Hi Stefan,

Sorry for the late replay, I totally missed it :-(.

Are you running the latest version 1.0.9 ?

Cheers
  Lars

**Comment by habakuk007** [comment]
Hello Lars,

yes, I'm using 1.0.9.

Ciao!
   Stefan

**Comment by LarsSkovslund** [comment]
Hi Stefan,

If you are still having this issue please try the new release 1.0.10 where the underlying nuget.exe has been updated to 3.3

cheers
  Lars
