### ISSUE TITLE
Referenced Project pdb Not Found

### ISSUE THREAD

**Issue by dansiegel** [LarsSkovslund/NuGet.Package.Builder#6]
With a Solution where Project A references Project B, a System.IO.FileNotFoundException is thrown as it cannot find the ProjectB.pdb. This occurs when the package.builder.json file's IncludeReferencedProjects is set to true. Both Project A & Project B are using the NuGet Package Builder and have a nuspec file.

**Comment by LarsSkovslund** [comment]
Hi Dan,

I just added two Class libraries A and B. A reference B and they both have Nuget.Package.Builder with IncludeReferencedProjects set to true and this works fine. I also tried to enable the Symbols to true and still no problem. 

Are you setting the UseNuspecFileOnly to true and including files through that?

Cheers
  Lars

**Comment by dansiegel** [comment]
Hi Lars,
The issue seems to be limited to the pdb file. With no real configuration the build process works just fine and will automatically pick up the dll and xml files for the project, as well as add a generic reference to the NuGet package(s) that the project relies on as well as the referenced project which also has a nuspec file. I realize you can create an actual symbols package. However if you just want to pick up the pdb file and stick it in the package it will work for a single file however it will not work for the Referenced Project. I've thrown up a [demo](https://github.com/dansiegel/packagedemo) for your reference.

```xml
<files>    
  <!-- The pdb file cannot be referenced from a project which other projects in the solution are referencing -->
  <file src="$id$.pdb" target="lib\portable-net45+win+wp80+MonoAndroid10+xamarinios10+MonoTouch10\" />

  <!-- There is no problem with content files being included in either nuget package -->
  <file src="ReadMe.md" target="content\portable-net45+win+wp80+MonoAndroid10+xamarinios10+MonoTouch10\" />
</files>
```

Two other things I wanted to bring up. 
1) It would be nice if the path were tokenized so I don't have to set the framework portion of the path.
2) Is there a way to get this to work with targeting multiple frameworks/profiles and assign the correct framework dependencies? As an example I may target Profile 78 and UWP from the same library. Both targets may need Newtonsoft.Json, and Profile 78 may need Microsoft.Net.Http while UWP does not.

**Comment by LarsSkovslund** [comment]
Hi Dan,

It seems that you have stumbled over a bug in `NuGet.exe`.
Running the nuget.exe command fails regardless:

```cmd
NuGet.exe pack "C:\packagedemo-master\NuGetLib\NuGetLib.csproj" -NoDefaultExcludes -Verbosity Detailed -Properties "Configuration=Debug;Platform=AnyCPU" -NonInteractive -OutputDirectory "C:\packagedemo-master\NuGetLib\bin\Debug" -basepath "C:\packagedemo-master\NuGetLib\bin\Debug" -IncludeReferencedProjects
```

1) This library basically wraps the NuGet.exe and calls it via MSBuild on compile time. This means that the behavior of the `nuspec` file is limited to what Nuget offers.
2) As far as I can tell there are no way of doing that.
