### ISSUE TITLE
Question about vcxproj

### ISSUE THREAD

**Issue by bv2012** [LarsSkovslund/NuGet.Package.Builder#7]
Does the Package builder work with C++ projects. Tried installing the Nuget into a vcxproj but looks like the nuspec file is not getting generated.

Any idea how I can do that ?

Best regards!
Beevee

**Comment by LarsSkovslund** [comment]
Hi Beevee,

I have not tried to use nuget with C++ CLR and my guess is the you would need to add the nuspec manually and set the ``UseNuspecFileOnly`` to ``true`` in the ``package.builder.json`` for it to work.

You would loose all ``$xx$`` variables and have to set values manually :-(

Let me know if this works.

Cheers
  Lars
